### PR TITLE
Add auto-deploy of microsite to GH Pages 🐙

### PR DESCRIPTION
**Pull request by kutyel**
Related to https://github.com/47deg/marlow/issues/406

I can't generate haddock docs yet because CI does not know about stack, maybe we chould find a way to generate the docs with Nix 🤔 (although I think the current `cachix-action` is already generating the haddock docs somewhere).

### CODE REVIEW

**Comment by calvellido** [comment]
Maybe this could be added to get Haskell in the mix:

https://github.com/actions/setup-haskell

**Comment by kutyel** [comment]
> Maybe this could be added to get Haskell in the mix:
> 
> https://github.com/actions/setup-haskell

I'm afraid that is the default GitHub action for Haskell, which uses Cabal 3.0, and right now our Haddock generations relies entirely on Stack 😕 

I don't think it would be ideal to mix build tools in the same CI 😂

**Comment by kutyel** [comment]
I see that it does not understand the `bundle` command... @calvellido should we try https://github.com/BryanSchuetz/jekyll-deploy-gh-pages instead? 🤔

**Comment by rachelcarmena** [comment]
Hi mates! Some comments:

- To solve the problem, try to add a previous step to install that command:
```
sudo apt-get update
sudo apt-get install ruby-dev
sudo gem install bundler --force
sudo gem update --system
```
- Try to separate build and deploy. 
- Build on:
```
on: pull_request
```
- Deploy (it will include build as well) on:
```
on:
  push:
    branches:
    - master
```
- `PUBLISH_BRANCH: gh-pages` can be `master`
- An idea: create a repository on your personal account to make tests with custom actions very quickly.

**Pull request merged**
