### PR TITLE
Various fixes to GraphQL introspection

### PR DESCRIPTION
**Pull request by serras**

### CODE REVIEW

**Comment by kutyel** [comment]
All the new builds are taking ~25m again 😢 I think we should go back to cachix! 🔥

**Comment by serras** [comment]
What about not caching .stack-work? That used to work fine.

**Comment by kutyel** [comment]
Looking at the Actions tab, none of the caches for stack seem to be working 🤷‍♂

**Comment by serras** [comment]
Could you try pushing something that doesn't change stack.yaml in this
branch to see whether it gets the right one?

**Comment by kutyel** [comment]
Now it worked, could it be that the cache is not persisted between PRs? That's a really strange behaviour from the Github Actions Cache plugin! 🤔

**Comment by serras** [comment]
My guess is that we were making a lot of changes in the stack.yaml files
lately, and that from now on it will stabilize.

**Pull request merged**
