### PR TITLE
Separate annotations from core schema type

### PR DESCRIPTION
**Pull request by serras**
Before definitions like the id for ProtoBuf were part of the schema. However, that meant that we could not retro-fit the same schema for different purposes. This PR separates these two concepts and updates the Template Haskell code, so examples don't need to change.

This change will be properly documented in #31

### CODE REVIEW

**Comment by serras** [comment]
The Travis failure is so weird. How can it fail in the PR but not in the branch? Furthermore, it seems completely non-reproducible in my machine, with either LTS or Nightly.

**Comment by serras** [comment]
Now I understand, the problem is that it's conflicting with the `seed` example, which is not yet merge.
@kutyel could you try adding `{-# language TypeFamilies #-}` to your Definition file in that example, and then run the build again? Thanks 🙇

**Comment by kutyel** [comment]
Apparently it didn't work 😖

**Comment by serras** [comment]
I am fairly confident that now it should work. Please review and merge if it's green :)

**Pull request merged**
