### PR TITLE
Port health check to use Servant + fix a few corner cases

### PR DESCRIPTION
**Pull request by serras**
You might be interested in this @andremarianiello 😉 

I added REST support to the the `health-check` example using the new Servant support. I can only say: it's awesome so easy it is, just specify routes and verbs and it works!

Well... I had to fix a couple of corner cases in the code, but that's how we make progress.

### CODE REVIEW

**Review by kutyel — APPROVED** [review]
:shipit:

**Comment by andremarianiello** [comment]
Looks sweet!

**Comment by andremarianiello** [comment]
Looking at what you had to do for a more real example, I wonder if the ServantRoute, ServantMethod, and ServantStatus types should all be combined into one. Having the path separate from the verb is harder to read (and more work to write) than just simply
```
'AnnMethod "MyService" "MyMethod" ('ServantRPCSettings '["my_method"] 'GET 200])
```
though maybe that is just me. I don't think it should necessarily be changed at this point, but I would be surprised if users complain about it. Though if they do, I bet someone will have good suggestions on how to improve the UX. Maybe its best to wait and see.

**Comment by serras** [comment]
I think that's a very good idea, I also felt that just 2 type families should be enough. Let me try to produce a patch and then @andremarianiello @kutyel you tell me what you think.

**Pull request merged**
